v3.0 -Updated to 2.18 from DSIXDA -Added RUUVEAL -Smali/Baksmali to 1.4.2 -Updated One S and One XL edifs

diff --git a/scripts/choose_single_deodex b/scripts/choose_single_deodex
--- a/scripts/choose_single_deodex
+++ b/scripts/choose_single_deodex
@@ -76,8 +76,41 @@ then
   cp -f ../tools/deodex_files/baksmali-$version.jar baksmali.jar
   cp -f ../tools/deodex_files/smali-$version.jar smali.jar
 
-  ../scripts/do_deodex_file $api_level $file_chosen system/framework
-  result=$?
+  try_again=y
+
+  while [ "$try_again" != "n" ]
+  do
+    echo
+    echo "Enter any JAR file dependencies separated by colon (Enter=none)."
+		echo "NOTE: To ignore errors, type 'ignore' by itself or after dependencies"
+		echo    
+		echo -n "$file_chosen > "
+    read classfiles
+    echo
+
+		if [ "$classfiles" == "ignore" ]
+		then
+			classfiles="none yes"
+		else
+			classfiles=`echo $classfiles | sed -e 's/ ignore/ yes/g'`
+		fi
+
+    ../scripts/do_deodex_file $api_level $file_chosen system/framework $classfiles 
+
+    result=$?
+
+    if [ "$result" == 1 ]
+    then
+      echo
+      echo -n "Try $file_chosen again (y/n)? (default: y): "
+      read try_again
+      echo
+    else
+      break
+    fi
+
+  done
+
   rm -f *smali.jar
 
 fi
diff --git a/scripts/zip_file_to_working_folder b/scripts/zip_file_to_working_folder
--- a/scripts/zip_file_to_working_folder
+++ b/scripts/zip_file_to_working_folder
@@ -45,10 +45,77 @@ echo "Creating working folder $build_dir ..."
 mkdir $build_dir
 
 echo
-echo "Extracting ROM ..."
-unzip -q original_update/$update_file -d $build_dir -x bootloader.img recovery.img recovery_signed.img userdata.img radio.img rcdata.img splash1.nb0 splash2.nb0 android-info.txt 2>/dev/null
+echo "Extracting ROM from ZIP file ..."
 
-if [ "$?" == "9" ]
+if [ `uname | grep CYGWIN` ]
+then
+
+  #
+  # Instead of 'unzip -qo' (the 'o' would force overwrite), show the user a prompt if a duplicate filename is encountered;
+  # e.g. In a case where we have /system/lib/libdivxdrm.so and /system/lib/libDivxDrm.so, it would ask to overwrite/rename
+  # or ignore one of them.  This way, the user won't be unaware of the duplicate file name.
+  #
+  # To show the prompt in the unzip command, disable the output to /dev/null. To prevent displaying warnings about excluded  
+  # files (because /dev/null is not used anymore) put them in the 'rm' command instead of in unzip's '-x' arguments.
+  #
+  # This is not a faster method than "unzip -q ... -x ... 2>/dev/null", but it prevents the kitchen from hanging at unzip.
+  #
+  # Also, this is just a workaround, it doesn't fix the duplicate file name issue. You have two options to fix the issue:
+  #
+  # 1) Use an operating system that uses case-sensitive file names (Linux or OS X)
+  # 2) In the Windows registry, set HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive to 0 and
+  #    reboot... but do this at your own risk.
+  #
+  unzip -q original_update/$update_file -d $build_dir 2>&1 | tee unzip.log
+  unzip_result=$?
+  
+  rm -f bootloader.img recovery.img recovery_signed.img userdata.img radio.img rcdata.img splash1.nb0 splash2.nb0 android-info.txt 
+
+  replace_count=`grep -c replace unzip.log`
+  rm -f unzip.log
+
+  if [ $replace_count -gt 0 ]
+  then
+    echo
+    echo
+    echo "WARNING"
+    echo "-------"
+    echo "One of the folders in your ZIP archive contains two files with the SAME NAME that differ"
+    echo "by upper and lower case, which is the reason you saw the prompt above.  Because Windows"
+    echo "is case-insensitive, it treats both files as a SINGLE file rather than two distinct"
+    echo "files!"
+    echo
+    echo "You can choose to ignore this issue, or quit. There are two ways to resolve this:"
+    echo 
+    echo "1) Use an operating system that treats file names as case-sensitive (Linux or OS X), OR"
+    echo "2) In the Windows registry, set: "
+    echo "   HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive to 0"
+    echo "   and reboot. However, this affects all of Windows - do this at your own risk!"
+    echo 
+    echo
+    echo -n "Do you wish to ignore this issue (y/n)? (default: n): "
+    read do_ignore
+
+    if [ "$do_ignore" != "y" ]
+    then
+      echo
+      echo "OK, aborting"
+      cd ..
+      exit 1
+    else
+      echo
+      echo "OK, ignoring it, but your new ROM may have stability issues!"
+    fi
+  fi
+
+else
+  unzip -q original_update/$update_file -d $build_dir -x bootloader.img recovery.img recovery_signed.img userdata.img radio.img rcdata.img splash1.nb0 splash2.nb0 android-info.txt 2>/dev/null
+
+  unzip_result=$?
+
+fi
+
+if [ "$unzip_result" == "9" ]
 then
   echo
   echo "Error: Cannot extract ROM!"
@@ -124,9 +191,16 @@ elif [ -e factoryfs.img ]
 then
   echo Found factoryfs.img
 
+  if [ -e hidden.img ]
+  then
+    echo "Found hidden.img"
+  else
+    echo "No hidden.img found"
+  fi
+
   if [ -e cache.img ]
   then
-    echo Found cache.img
+    echo "Found cache.img"
   else
     echo "Warning: No cache.img found"
   fi
@@ -177,6 +251,20 @@ then
   cd ..
   scripts/simg_ext4_files_to_working_folder no_create $2
   exit $?
+
+
+
+#
+# Check for certain Samsung factory images
+#
+elif [ -e system.rfs ]
+then
+
+  cd ..
+  echo "Found system.rfs"
+  scripts/rfs_files_to_working_folder no_create $2
+  exit $?
+
 
 
 #
